format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$fill\
$php\
$jobs\
$cmd_duration\
$line_break\
$character"""

command_timeout = 3600

[directory]
style = 'bold green'
truncate_to_repo = false
truncation_length = 9
truncation_symbol = '../'

[git_branch]
symbol = ' '
format = '[$symbol$branch ](blue)'

[git_status]
style = 'fg:yellow'
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = "-"
style = '#303030'

[php]
symbol = ' '
style = '#c6b6ee'
format = ' [$symbol($version)]($style) '
