format = """
$directory\
$git_branch\
$git_status\
$fill\
$php\
$jobs\
$cmd_duration\
$line_break\
$character"""

command_timeout = 3600

[fill]
symbol = "-"
style = '#303030'

[git_branch]
symbol = ' '
format = '[$symbol$branch ](yellow)'

[php]
symbol = ' '
style = '#c6b6ee'
format = ' [$symbol($version)]($style)'
