set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi

set -g status-position top
set -g status-right-length 200
set -g status-bg colour236
set -g status-left "#[fg=colour248] #S "
set -g status-right "#[fg=colour250] %a %b %d, %I:%M "
set -g window-status-current-format " #[fg=colour250,bold][#I:#W]"
set -g window-status-format "#[fg=colour247,nobold]  #I:#W "
set -g message-command-style "fg=${white},bg=${black}"
set -g message-style "fg=${black},bg=${red}"
set -g mode-style "bg=${black},fg=${yellow}"
set -g pane-active-border-style "fg=green"
set -g pane-border-style "fg=colour238"
set -g pane-border-lines single

# Message display time. Default is 750, Sensible uses 4000
set-option -g display-time 1000

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# session list
bind C-j choose-tree

# splits
bind - split-window -v -c '#{pane_current_path}'
bind \\ split-window -h -c '#{pane_current_path}'
bind c new-window -c "#{pane_current_path}"

# Resize panes
bind -n S-Left resize-pane -L 8
bind -n S-Right resize-pane -R 8
bind -n S-Down resize-pane -D 4
bind -n S-Up resize-pane -U 4

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
